import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { leads, type Lead } from "~/lead-data";

export const Route = createFileRoute('/dashboard')({ component: Dashboard });
type Stage = 'new' | 'contacted' | 'engaged' | 'proposal' | 'won' | 'lost';
type Deal = { id:string; name:string; value:number; stage:Stage; created:string };
const stages: {key:Stage; icon:string; label:string; tone:string}[] = [
 {key:'new',icon:'🔍',label:'New Leads',tone:'blue'}, {key:'contacted',icon:'📞',label:'Contacted',tone:'violet'}, {key:'engaged',icon:'💬',label:'Engaged',tone:'amber'}, {key:'proposal',icon:'📩',label:'Proposal Sent',tone:'pink'}, {key:'won',icon:'✅',label:'Closed Won',tone:'green'}, {key:'lost',icon:'❌',label:'Closed Lost',tone:'red'}
];
const initial: Deal[] = [];
function Dashboard(){
 const [deals,setDeals]=useState<Deal[]>(initial); const [ready,setReady]=useState(false);
 const [name,setName]=useState(''); const [value,setValue]=useState('2500'); const [stage,setStage]=useState<Stage>('new'); const [notice,setNotice]=useState('');
 useEffect(()=>{try{const raw=localStorage.getItem('ch-pipeline-deals'); if(raw)setDeals(JSON.parse(raw))}catch{} setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem('ch-pipeline-deals',JSON.stringify(deals))},[deals,ready]);
 const won=useMemo(()=>deals.filter(d=>d.stage==='won'),[deals]); const revenue=won.reduce((s,d)=>s+d.value,0); const pct=Math.min(100,revenue/100); const total=deals.length;
 const closeRate=total?Math.round(won.length/total*100):0; const needed=Math.max(0,Math.ceil((10000-revenue)/2500));
 const add=(e:React.FormEvent)=>{e.preventDefault(); if(!name.trim()||!Number(value))return; setDeals([{id:crypto.randomUUID(),name:name.trim(),value:Number(value),stage,created:new Date().toISOString()},...deals]);setName('');setValue('2500');setNotice('Deal added');setTimeout(()=>setNotice(''),1800)};
 const addLead=(lead:Lead)=>{setDeals([{id:crypto.randomUUID(),name:lead.name,value:2500,stage:'new',created:new Date().toISOString()},...deals]);setNotice(`${lead.name} added to pipeline`);setTimeout(()=>setNotice(''),1800)};
 return <main className="dash"><header className="dash-head"><div><div className="eyebrow">CH BUSINESS SERVICES · REVENUE COMMAND CENTER</div><h1>Pipeline <span>Dashboard</span></h1><p className="sub">A live view of the deals moving CH Business Services toward $10K a week.</p></div><a className="dash-link" href="/">← Back to home</a></header>
 <section className={'revenue '+(pct<25?'low':pct<50?'mid':'high')}><div className="revenue-top"><div><span className="section-kicker">THIS WEEK'S REVENUE</span><strong>${revenue.toLocaleString()} <em>/ $10,000</em></strong></div><b>{Math.round(pct)}%</b></div><div className="progress"><i style={{width:`${pct}%`}}/></div><div className="revenue-foot"><span>{revenue>=10000?'Target reached — keep closing.':`${needed} ${needed===1?'deal':'deals'} needed at $2,500 avg.`}</span><span>Resets weekly · saved on this device</span></div></section>
 <section className="dash-stats"><div><span>Total leads in pipeline</span><b>{total}</b></div><div><span>Deals needed to hit $10K</span><b>{needed}</b><small>at $2,500 avg</small></div><div><span>Current close rate</span><b>{closeRate}%</b><small>{won.length} won of {total}</small></div></section>
 <section className="dash-section"><div className="section-title"><div><span className="section-kicker">PIPELINE</span><h2>Move every opportunity forward</h2></div><span className="live"><i/> Live · local storage</span></div><div className="kanban">{stages.map(s=><div className={'kanban-col '+s.tone} key={s.key}><div className="col-head"><span>{s.icon} {s.label}</span><b>{deals.filter(d=>d.stage===s.key).length}</b></div><div className="cards">{deals.filter(d=>d.stage===s.key).map(d=><article className="deal-card" key={d.id}><strong>{d.name}</strong>{d.value>0&&<span>${d.value.toLocaleString()}</span>}<select value={d.stage} onChange={e=>setDeals(deals.map(x=>x.id===d.id?{...x,stage:e.target.value as Stage}:x))}>{stages.map(x=><option value={x.key} key={x.key}>{x.label}</option>)}</select></article>)}{!deals.some(d=>d.stage===s.key)&&<p className="empty">No deals here yet</p>}</div></div>)}</div></section>
 <section className="lower-grid"><div className="panel"><div className="section-title"><div><span className="section-kicker">QUICK ADD</span><h2>Log a new deal</h2></div>{notice&&<span className="notice">✓ {notice}</span>}</div><form className="deal-form" onSubmit={add}><label>Business name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Aqua Austin Plumbing" required/></label><label>Deal value ($)<input type="number" min="1" value={value} onChange={e=>setValue(e.target.value)} required/></label><label>Stage<select value={stage} onChange={e=>setStage(e.target.value as Stage)}>{stages.map(s=><option value={s.key} key={s.key}>{s.icon} {s.label}</option>)}</select></label><button type="submit">Add to pipeline +</button></form></div><div className="panel"><div className="section-title"><div><span className="section-kicker">CLOSED WON</span><h2>This week's deals</h2></div><b className="panel-total">${revenue.toLocaleString()}</b></div>{won.length?<div className="deal-table">{won.map(d=><div key={d.id}><span>{d.name}<small>{new Date(d.created).toLocaleDateString()}</small></span><b>${d.value.toLocaleString()}</b></div>)}</div>:<p className="empty large">Closed deals will appear here.</p>}</div></section>
 <section className="dash-section lead-bank"><div className="section-title"><div><span className="section-kicker">LEAD BANK · 60 QUALIFIED PROSPECTS</span><h2>Ready-to-contact leads</h2></div><span className="muted">Batch 1 + Batch 2</span></div><div className="lead-table"><div className="lead-row lead-head"><span>Business</span><span>City</span><span>Niche</span><span>Phone</span><span/></div>{leads.map((l,i)=><div className="lead-row" key={i}><strong>{l.name}</strong><span>{l.city}</span><span>{l.niche}</span><a href={'tel:'+l.phone}>{l.phone}</a><button onClick={()=>addLead(l)}>Add to Pipeline</button></div>)}</div></section><footer>CH Business Services · Build systems that turn attention into revenue.</footer></main>
}
